export type sampleDetailsType = {
  karat: number;
  gold: number;
  silver: number;
  copper: number;
  zinc: number;
  cadmium: number;
  iridium: number;
  ruthenium: number;
  osmium: number;
  lead: number;
  iron: number;
  nickel: number;
  rhodium: number;
  manganese: number;
  tin: number;
  platinum: number;
  bismuth: number;
  palladium: number;
  cobalt: number;
  rhenium: number;
};
